create table if not exists public.gallery_images (
  id bigint generated by default as identity primary key,
  image_url text not null,
  storage_path text unique,
  alt_text text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.gallery_images enable row level security;

create policy if not exists "Public can view gallery images"
on public.gallery_images
for select
to public
using (true);

create policy if not exists "Admins can insert gallery images"
on public.gallery_images
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles
    where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
  )
);

create policy if not exists "Admins can delete gallery images"
on public.gallery_images
for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
  )
);

insert into storage.buckets (id, name, public)
values ('gallery-images', 'gallery-images', true)
on conflict (id) do nothing;

create policy if not exists "Public can view gallery storage"
on storage.objects
for select
to public
using (bucket_id = 'gallery-images');

create policy if not exists "Admins can upload gallery storage"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'gallery-images'
  and exists (
    select 1
    from public.profiles
    where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
  )
);

create policy if not exists "Admins can delete gallery storage"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'gallery-images'
  and exists (
    select 1
    from public.profiles
    where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
  )
);
